Repository snifour/kt-wiz-snifour, pull requests merged in 2024-12, with the labels that each got.

#7 feat: 공통 헤더 레이아웃(#2)
  public/assets/img-logo-black.svg
  public/assets/img-logo.svg
  src/features/common/Header.tsx
Labels: ✨ Feature

#10 Features/Game내부 경기 일정 부분 퍼블리싱/#3
  package-lock.json
  package.json
  src/assets/data/broadcastChannels.json
  src/components/ui/button/button.tsx
  src/components/ui/card/card.tsx
  src/components/ui/carousel/MatchInfoCarousel.tsx
  src/components/ui/carousel/carousel.tsx
  src/components/ui/index.ts
  src/features/game/components/MatchCalendar.tsx
  src/features/game/components/MatchScheduleTab.tsx
Labels: ✨ Feature

#13 feat: 리액트 라우터 설정(#11)
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/index.css
  src/pages/HomePage.tsx
Labels: ✨ Feature

#15 style: 공통 헤더 z-index 설정(#14)
  src/features/common/Header.tsx
Labels: 🐞 BugFix

#17 Features/#12
  src/App.tsx
  src/components/ui/index.ts
  src/components/ui/table/table.tsx
  src/features/common/Breadcrumb.tsx
  src/features/common/SubTitle.tsx
  src/features/game/components/BoxScoreTab.tsx
  src/features/game/components/MatchScheduleTab.tsx
  src/features/game/components/table/BattingRecordTable.tsx
  src/features/game/components/table/KeyRecordsTable.tsx
  src/features/game/components/table/MatchScoreTable.tsx
  src/features/game/components/table/PitchingRecordTable.tsx
  src/features/game/components/table/index.ts
Labels: ✨ Feature

#18 Features/#5
  package-lock.json
  package.json
  src/assets/hooks/useKakaoLoader.tsx
  src/assets/images/ktwizpark.jpg
  src/pages/wizPark/ParkIntro.tsx
  src/pages/wizPark/ParkLocation.tsx
  tsconfig.json
Labels: ✨ Feature

#19 Features/#9 메인 페이지 레이아웃
  package-lock.json
  package.json
  src/components/ui/index.ts
  src/components/ui/popover/popover.tsx
  src/components/ui/select/select.tsx
  src/features/common/Footer.tsx
  src/features/common/Header.tsx
  src/features/home/components/MainImageSlider.tsx
  src/features/home/components/MatchInfo.tsx
  src/features/home/components/TeamRanking.tsx
  src/features/home/components/WizGallery.tsx
  src/features/home/components/WizVideo.tsx
  src/features/home/index.ts
  src/pages/HomePage.tsx
Labels: ✨ Feature

#21 feat: 공통 색상 셋팅(#20)
  tailwind.config.js
Labels: ✨ Feature

#25 Features/#23
  public/assets/sns/ico-facebook@2x.png
  public/assets/sns/ico-instagram@2x.png
  public/assets/sns/ico-naver@2x.png
  public/assets/sns/ico-youtube@2x.png
  src/App.tsx
  src/features/common/Footer.tsx
  src/features/home/components/MatchInfo.tsx
  src/features/home/components/TeamRanking.tsx
  src/features/home/components/WizGallery.tsx
  src/features/home/components/WizVideo.tsx
Labels: ✨ Feature

#27 Features/#22: 경기 일정, 박스 스코어 색상 변경
  src/components/ui/carousel/MatchInfoCarousel.tsx
  src/features/common/Breadcrumb.tsx
  src/features/common/SubTitle.tsx
  src/features/common/TeamInfo.tsx
  src/features/game/components/BoxScoreTab.tsx
  src/features/game/components/MatchCalendar.tsx
  src/features/game/components/MatchScheduleTab.tsx
  src/features/game/components/table/BattingRecordTable.tsx
  src/features/game/components/table/KeyRecordsTable.tsx
  src/features/game/components/table/MatchScoreTable.tsx
  src/features/game/components/table/PitchingRecordTable.tsx
Labels: ✨ Feature, 🛠️ Refactor

#28 Features/#26: 응원가 페이지 레이아웃
  package-lock.json
  package.json
  public/assets/emblems/ktwiz.svg
  public/assets/players/강백호.webp
  src/App.tsx
  src/components/ui/index.ts
  src/components/ui/tabs/tabs.tsx
  src/features/common/Breadcrumb.tsx
  src/features/common/Header.tsx
  src/features/home/components/MainImageSlider.tsx
  src/features/song/components/NowPlaying.tsx
  src/features/song/components/SongBoard.tsx
  src/features/song/index.ts
  src/features/song/types/index.ts
  src/pages/player/CheerSong.tsx
Labels: ✨ Feature

#31 Features/#30 메인 페이지 이미지 바인딩 및 자동 슬라이드
  package-lock.json
  package.json
  public/assets/main/2024_post_bg_web.png
  public/assets/main/img-banner-store@2x.png
  public/assets/main/player@2x.png
  src/App.tsx
  src/features/common/Header.tsx
  src/features/home/components/MainImageSlider.tsx
  src/index.css
Labels: ✨ Feature

#35 Features/#29 Game/정규리그/관전 포인트 퍼블리싱
  public/assets/emblems/kiwoom.svg
  public/assets/emblems/lgtwins.svg
  public/assets/ground.png
  src/App.tsx
  src/components/ui/carousel/MatchInfoCarousel.tsx
  src/features/common/TeamInfo.tsx
  src/features/game/BoxScoreTab.tsx
  src/features/game/MatchScheduleTab.tsx
  src/features/game/WatchPointTab.tsx
  src/features/game/components/BoxScoreTab.tsx
  src/features/game/components/MatchBoard.tsx
  src/features/game/components/TeamLineup.tsx
  src/features/game/components/table/MatchSummaryTable.tsx
  src/features/game/components/table/index.ts
  src/features/game/index.tsx
Labels: ✨ Feature

#36 Features/#32
  public/assets/wallpaper/calendar-1920x1080.png
  public/assets/wallpaper/paper-1920x1080.jpg
  src/App.tsx
  src/features/common/Header.tsx
  src/features/common/SubTitle.tsx
  src/pages/ktwiz/WallpaperPage.tsx
  src/pages/player/CheerSongPage.tsx
  src/pages/wizPark/ParkIntroPage.tsx
  src/pages/wizPark/ParkLocationPage.tsx
  src/pages/wizPark/ParkingPage.tsx
Labels: ✨ Feature

#44 Features/#41
  src/App.tsx
  src/assets/hooks/useTabFromUrl.tsx
  src/features/common/Banner.tsx
  src/features/common/Layout.tsx
  src/features/game/css/game.css
  src/pages/game/RegularGamePage.tsx
  src/pages/media/FirstPitch.tsx
  src/pages/media/Highlight.tsx
  src/pages/media/News.tsx
  src/pages/media/Photo.tsx
  src/pages/media/Story.tsx
  src/pages/wizPark/ParkLocationPage.tsx
Labels: ✨ Feature

#42 Features/#38
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/features/game/BoxScoreTab.tsx
  src/features/game/MatchScheduleTab.tsx
  src/features/game/WatchPointTab.tsx
  src/features/game/apis/matchSchedule.ts
  src/features/game/components/MatchCalendar.tsx
  src/features/game/components/calender/CalendarHeader.tsx
  src/features/game/components/calender/MatchCalendar.tsx
  src/features/game/components/calender/MatchCalendarCell.tsx
  src/features/game/components/calender/index.ts
  src/features/game/index.tsx
Labels: ✨ Feature

#50 fix: import 잘못된 경로 수정(#48)
  src/features/game/BoxScoreTab.tsx
  src/features/game/MatchScheduleTab.tsx
  src/features/game/WatchPointTab.tsx
  src/features/game/index.ts
Labels: 🐞 BugFix

#54 Features/#49 경기 일정 캐러셀 api 연동
  package-lock.json
  package.json
  src/components/ui/carousel/MatchInfoCarousel.tsx
  src/features/common/TeamInfo.tsx
  src/features/game/apis/matchSchedule.ts
  src/features/game/components/CarouselCard.tsx
  src/features/game/components/calender/CalendarHeader.tsx
  src/features/game/components/calender/CalenderBody.tsx
  src/features/game/components/calender/MatchCalendar.tsx
  src/features/game/components/calender/MatchCalendarCell.tsx
  src/features/game/components/calender/index.ts
  src/features/game/components/index.ts
  src/features/game/types/index.ts
  src/store/useMatchStore.ts
Labels: ✨ Feature, 📪 API, 🛠️ Refactor

#57 Features/#55 투수 순위 레이아웃 및 api 연동
  package-lock.json
  package.json
  src/App.tsx
  src/constants/api-url.ts
  src/constants/player-rank-colums.tsx
  src/features/common/SubTabsTrigger.tsx
  src/features/common/SubTitle.tsx
  src/features/common/types/Pitchers.ts
  src/features/game/BatterRankingTab.tsx
  src/features/game/CrowdRankingTab.tsx
  src/features/game/PitcherRankingTab.tsx
  src/features/game/RankingTab.tsx
  src/features/game/TeamRankingTab.tsx
  src/features/game/components/index.ts
  src/features/game/components/ranking/common/CustomTooltip.tsx
  src/features/game/components/ranking/common/PlayerRankingTable.tsx
  src/features/game/components/ranking/common/PlayerScatterChart.tsx
  src/features/game/components/ranking/common/RankingCard.tsx
  src/features/game/components/ranking/index.ts
  src/features/game/components/ranking/pitcher/AllPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/KTPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/SortingTrigger.tsx
  src/features/game/components/ranking/team/TeamBatterRankingTable.tsx
  src/features/game/components/ranking/team/TeamPitcherRankingTable.tsx
  src/features/game/components/ranking/team/TeamRankingTable.tsx
  src/features/game/components/ranking/team/TeamVSTable.tsx
  src/features/game/index.ts
  src/features/game/types/index.ts
  src/pages/game/regular/RegularGamePage.tsx
Labels: ✨ Feature, 📪 API

#59 Features/#56 정규리그 관전 포인트 API 연동
  src/features/common/TeamInfo.tsx
  src/features/game/BoxScoreTab.tsx
  src/features/game/MatchScheduleTab.tsx
  src/features/game/WatchPointTab.tsx
  src/features/game/apis/index.ts
  src/features/game/apis/match-schedule.ts
  src/features/game/apis/watch-point.ts
  src/features/game/components/TeamLineup.tsx
  src/features/game/components/calender/MatchCalendar.tsx
  src/features/game/components/carousel/CarouselCard.tsx
  src/features/game/components/carousel/MatchInfoCarousel.tsx
  src/features/game/components/carousel/index.ts
  src/features/game/components/index.ts
  src/features/game/components/ranking/team/TeamVSTable.tsx
  src/features/game/components/table/MatchSummaryTable.tsx
  src/features/game/components/watch-point/MatchBoard.tsx
  src/features/game/components/watch-point/StartingPitcher.tsx
  src/features/game/components/watch-point/TeamLineup.tsx
  src/features/game/components/watch-point/index.ts
  src/features/game/types/match-schedule.ts
  src/features/game/types/watch-point.ts
Labels: ✨ Feature, 📪 API, 🛠️ Refactor

#60 Features/#58 타자 순위 레이아웃 및 api 바인딩
  src/constants/player-rank-colums.tsx
  src/features/common/types/Pitchers.ts
  src/features/common/types/batters.ts
  src/features/game/BatterRankingTab.tsx
  src/features/game/RankingTab.tsx
  src/features/game/components/ranking/batter/AllBatterRankingTab.tsx
  src/features/game/components/ranking/batter/BatterRankingTab.tsx
  src/features/game/components/ranking/batter/KTBatterRankingTab.tsx
  src/features/game/components/ranking/common/CustomTooltip.tsx
  src/features/game/components/ranking/common/PlayerRankingTable.tsx
  src/features/game/components/ranking/common/PlayerScatterChart.tsx
  src/features/game/components/ranking/common/RankingCard.tsx
  src/features/game/components/ranking/common/SortingTrigger.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/ranking/index.ts
  src/features/game/components/ranking/pitcher/AllPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/KTPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/PitcherRankingTab.tsx
  src/features/game/components/ranking/team/TeamBatterRankingTable.tsx
  src/features/game/components/ranking/team/TeamPitcherRankingTable.tsx
  src/features/game/components/ranking/team/TeamRankingTab.tsx
  src/features/game/index.ts
  src/features/game/types/match-schedule.ts
Labels: ✨ Feature, 📪 API

#63 Features/#61 관중 현황 페이지 레이아웃 및 api 연결
  package-lock.json
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
  src/components/ui/select/select.tsx
  src/constants/seasons.ts
  src/features/game/components/ranking/common/CustomIndicator.tsx
  src/features/game/components/ranking/common/CustomTooltip.tsx
  src/features/game/components/ranking/common/PlayerScatterChart.tsx
  src/features/game/components/ranking/crowd/CrowdRankingChart.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTable.tsx
  src/features/game/components/ranking/index.ts
  src/features/game/components/ranking/team/TeamRankingTable.tsx
  src/features/game/components/ranking/team/TeamVSTable.tsx
  src/features/game/types/crowd-ranking.ts
  src/features/game/types/match-schedule.ts
  src/features/game/types/team-ranking.ts
  src/pages/game/regular/RegularGamePage.tsx
Labels: ✨ Feature, 📪 API

#65 Features/#62 코치 페이지, 코치 상세 페이지
  src/App.tsx
  src/features/media/common/SearchBar.tsx
  src/features/player/apis/coach.ts
  src/features/player/apis/index.ts
  src/features/player/components/PlayerList.tsx
  src/features/player/components/index.ts
  src/features/player/types/player.ts
  src/pages/player/CoachPage.tsx
  src/pages/player/id/CoachDetailPage.tsx
Labels: ✨ Feature, 📪 API

#67 Features/#40
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
  src/constants/player-rank-colums.tsx
  src/features/common/TeamInfo.tsx
  src/features/game/BoxScoreTab.tsx
  src/features/game/apis/boxScore.ts
  src/features/game/components/carousel/CarouselCard.tsx
  src/features/game/components/carousel/MatchInfoCarousel.tsx
  src/features/game/components/ranking/batter/AllBatterRankingTab.tsx
  src/features/game/components/ranking/batter/BatterRankingTab.tsx
  src/features/game/components/ranking/batter/KTBatterRankingTab.tsx
  src/features/game/components/ranking/common/CustomTooltip.tsx
  src/features/game/components/ranking/common/PlayerRankingTable.tsx
  src/features/game/components/ranking/common/PlayerScatterChart.tsx
  src/features/game/components/ranking/common/RankingCard.tsx
  src/features/game/components/ranking/common/SortingTrigger.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/ranking/pitcher/AllPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/KTPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/PitcherRankingTab.tsx
  src/features/game/components/ranking/team/TeamRankingTab.tsx
  src/features/game/components/table/BattingRecordTable.tsx
  src/features/game/components/table/KeyRecordsTable.tsx
  src/features/game/components/table/MatchScoreTable.tsx
  src/features/game/components/table/PitchingRecordTable.tsx
  src/features/game/components/watch-point/MatchBoard.tsx
  src/features/game/types/BoxScoreData.ts
  src/pages/game/regular/RegularGamePage.tsx
Labels: ✨ Feature, 📪 API

#69 Features/#66 Coach API 호출 함수 Hooks 분리
  src/assets/hooks/useCoach.tsx
  src/assets/hooks/useCoachList.tsx
  src/components/ui/carousel/carousel.tsx
  src/pages/player/CoachPage.tsx
  src/pages/player/id/CoachDetailPage.tsx
Labels: ✨ Feature, 📪 API, 🛠️ Refactor

#71 Features/#64 api 호출 분리 및 테이블 통일
  src/assets/data/__test__/mockRanking.json
  src/assets/hooks/ranking/index.ts
  src/assets/hooks/ranking/useBatterRank.tsx
  src/assets/hooks/ranking/useCrowdRank.tsx
  src/assets/hooks/ranking/usePitcherRank.tsx
  src/assets/hooks/ranking/useTeamRank.tsx
  src/assets/hooks/ranking/useTeamVS.tsx
  src/assets/hooks/ranking/useTopBatterRank.tsx
  src/assets/hooks/ranking/useTopPitcherRank.tsx
  src/constants/crowd-columns.tsx
  src/constants/team-rank-colums.tsx
  src/constants/team-vs-order.ts
  src/features/common/DataTable.tsx
  src/features/common/SortableTable.tsx
  src/features/common/types/pitchers.ts
  src/features/game/apis/ranking/batter.ts
  src/features/game/apis/ranking/crowd.ts
  src/features/game/apis/ranking/pitcher.ts
  src/features/game/apis/ranking/team.ts
  src/features/game/components/ranking/batter/AllBatterRankingTab.tsx
  src/features/game/components/ranking/batter/BatterRankingTab.tsx
  src/features/game/components/ranking/batter/KTBatterRankingTab.tsx
  src/features/game/components/ranking/common/RankingCard.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTable.tsx
  src/features/game/components/ranking/index.ts
  src/features/game/components/ranking/pitcher/AllPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/KTPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/PitcherRankingTab.tsx
  src/features/game/components/ranking/team/TeamBatterRankingTable.tsx
  src/features/game/components/ranking/team/TeamPitcherRankingTable.tsx
  src/features/game/components/ranking/team/TeamRankingTable.tsx
  src/features/game/components/ranking/team/TeamVSTable.tsx
Labels: 🛠️ Refactor

#74 Features/#70 응원단 페이지 레이아웃
  package-lock.json
  package.json
  src/App.tsx
  src/features/player/types/cheerleader.ts
  src/pages/player/CheerLeaderPage.tsx
  tsconfig.app.json
Labels: ✨ Feature

#75 Features/#72 테이블 디자인 공통화
  package-lock.json
  src/constants/batting-record-columns.ts
  src/constants/pitching-record-columns.ts
  src/constants/starting-pitcher-columns.ts
  src/features/common/CustomSelect.tsx.tsx
  src/features/common/DataTable.tsx
  src/features/game/BoxScoreTab.tsx
  src/features/game/RankingTab.tsx
  src/features/game/WatchPointTab.tsx
  src/features/game/components/calender/CalendarHeader.tsx
  src/features/game/components/calender/MatchCalendar.tsx
  src/features/game/components/calender/MatchCalendarCell.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/table/BattingRecordTable.tsx
  src/features/game/components/table/KeyRecordsTable.tsx
  src/features/game/components/table/PitchingRecordTable.tsx
  src/features/game/components/watch-point/StartingPitcher.tsx
  src/features/game/components/watch-point/StartingPitcherTable.tsx
  src/features/game/components/watch-point/index.ts
  src/features/game/hooks/useCoach.tsx
  src/features/game/hooks/useCoachList.tsx
  src/features/game/types/BoxScoreData.ts
  src/features/player/components/PlayerList.tsx
  src/pages/player/CoachPage.tsx
  src/pages/player/id/CoachDetailPage.tsx
Labels: ✨ Feature, 🛠️ Refactor

#79 Features/#76 모든 페이지에 상단 배너 적용
  src/features/home/components/WizParkMap.tsx
  src/pages/ktwiz/WallpaperPage.tsx
  src/pages/player/CoachPage.tsx
  src/pages/wizPark/ParkIntroPage.tsx
  src/pages/wizPark/ParkLocationPage.tsx
  src/pages/wizPark/ParkingPage.tsx
Labels: ✨ Feature

#81 Features/#78 응원단 페이지 디자인 수정 및 컴포넌트 분리
  src/features/player/components/CheerleaderDialog.tsx
  src/pages/player/CheerLeaderPage.tsx
Labels: 🛠️ Refactor

#82 Features/#76 익산 야구장 퍼블리싱
  src/App.tsx
  src/features/wizPark/IksanParkMap.tsx
  src/pages/wizPark/IksanStadiumPage.tsx
  src/pages/wizPark/ParkLocationPage.tsx
Labels: ✨ Feature

#85 Features/#16 소개페이지 퍼블리싱
  public/assets/Ktwiz/Players.jpg
  public/assets/Ktwiz/Stadium.jpg
  public/assets/Ktwiz/TeamLogo.jpg
  src/App.tsx
  src/pages/ktwiz/TeamHistory.tsx
  src/pages/ktwiz/TeamIntroduce.tsx
Labels: ✨ Feature

#88 Features/#87 메인페이지 반응형 레이아웃
  src/App.tsx
  src/constants/nav-menus.ts
  src/features/common/Footer.tsx
  src/features/common/header/Header.tsx
  src/features/common/header/MobileHeader.tsx
  src/features/common/header/Sidebar.tsx
  src/features/common/header/WebHeader.tsx
  src/features/home/components/MainImageSlider.tsx
  src/features/home/components/MatchInfo.tsx
  src/features/home/components/RecentMatches.tsx
  src/features/home/components/TeamRanking.tsx
  src/features/home/components/WizGallery.tsx
  src/features/home/components/WizVideo.tsx
  src/pages/HomePage.tsx
Labels: ✨ Feature

#89 Features/#84 팀 순위 투수 기록 시각화
  src/assets/data/__test__/season-team-rank/seasonPitcher.json
  src/constants/chart-config.ts
  src/features/common/CustomBarChart.tsx
  src/features/common/SubTabsTrigger.tsx
  src/features/game/components/ranking/team/TeamPitcherRankingTable.tsx
  src/features/game/components/table/MatchScoreTable.tsx
  src/features/player/components/PlayerRecordChart.tsx
  src/features/player/types/record.ts
Labels: ✨ Feature

#94 Features/#91 월페이퍼/주차예약/응원가 페이지 반응형
  src/App.tsx
  src/components/ui/card/card.tsx
  src/components/ui/tabs/tabs.tsx
  src/features/common/Banner.tsx
  src/features/common/Breadcrumb.tsx
  src/features/common/SubTitle.tsx
  src/features/common/header/Sidebar.tsx
  src/features/song/components/SongBoard.tsx
  src/pages/ktwiz/WallpaperPage.tsx
  src/pages/player/CheerSongPage.tsx
  src/pages/wizPark/ParkingPage.tsx
Labels: ✨ Feature

#95 Features/#93 WizPark 탭 내부 전체 페이지 반응형 설정
  src/features/game/MatchScheduleTab.tsx
  src/features/home/components/WizParkMap.tsx
  src/features/wizPark/IksanParkMap.tsx
  src/pages/wizPark/IksanStadiumPage.tsx
  src/pages/wizPark/ParkIntroPage.tsx
  src/pages/wizPark/ParkLocationPage.tsx
  src/pages/wizPark/ParkingPage.tsx
Labels: ✨ Feature

#98 Features/#97 순위 기록/타자, 투수 순위 부분 API 호출 및 데이터 바인딩
  src/assets/data/__test__/season-team-rank/seasonBatter.json
  src/assets/data/__test__/season-team-rank/seasonPitcher.json
  src/constants/chart-config.ts
  src/constants/columns/team-rank-colums.tsx
  src/features/common/CustomBarChart.tsx
  src/features/common/DataTable.tsx
  src/features/game/components/ranking/common/TeamRankingView.tsx
  src/features/game/components/ranking/team/TeamBatterRankingView.tsx
  src/features/game/components/ranking/team/TeamPitcherRankingView.tsx
  src/features/player/types/record.ts
  src/pages/ktwiz/TeamIntroduce.tsx
Labels: ✨ Feature, 📪 API

#100 Features/#96 선수 상세보기 페이지 데이터 연결
  src/App.tsx
  src/constants/columns/record-columns.tsx
  src/constants/columns/season-summary-columns.tsx
  src/features/common/CustomBarChart.tsx
  src/features/common/CustomLineChart.tsx
  src/features/game/components/ranking/common/TeamRankingView.tsx
  src/features/player/CatcherTab.tsx
  src/features/player/InfielderTab.tsx
  src/features/player/OutfielderTab.tsx
  src/features/player/apis/player.ts
  src/features/player/components/PlayerList.tsx
  src/features/player/components/PlayerProfile.tsx
  src/features/player/components/PlayerRecordChart.tsx
  src/features/player/components/RecordTableAccordion.tsx
  src/features/player/hooks/useCoach.tsx
  src/features/player/hooks/useCoachList.tsx
  src/features/player/hooks/usePlayer.tsx
  src/features/player/hooks/usePlayerList.tsx
  src/features/player/types/detail.ts
  src/features/player/types/list.ts
  src/features/player/types/record.ts
  src/pages/player/CoachPage.tsx
  src/pages/player/PitcherPage.tsx
  src/pages/player/PlayerListPage.tsx
  src/pages/player/detail/CoachDetailPage.tsx
  src/pages/player/detail/PlayerDetailPage.tsx
  src/pages/player/detail/TeamMemberDetailPage.tsx
Labels: 🐞 BugFix, 📪 API

#102 Features/#99 관전포인트 API 데이터 바인딩 확인 및 반응형 적용
  src/features/common/TeamInfo.tsx
  src/features/game/WatchPointTab.tsx
  src/features/game/components/table/MatchSummaryTable.tsx
  src/features/game/components/watch-point/MatchBoard.tsx
  src/features/game/components/watch-point/TeamLineup.tsx
  src/features/game/hooks/watch-point/useWatchPoint.tsx
  src/features/player/hooks/useCoachList.tsx
  src/pages/player/CoachPage.tsx
Labels: ✨ Feature, 📪 API, 🛠️ Refactor

#103 Features/#101 선수페이지 반응형 & UI 변경
  package-lock.json
  package.json
  src/components/ui/progress.tsx
  src/components/ui/table/table.tsx
  src/features/common/ChartLabelList.tsx
  src/features/common/CustomBarChart.tsx
  src/features/common/CustomLineChart.tsx
  src/features/common/DataTable.tsx
  src/features/player/components/PlayerProfile.tsx
  src/features/player/components/PlayerRecordChart.tsx
  src/features/player/components/RecordTableAccordion.tsx
  src/features/player/components/SeasonSummary.tsx
  src/features/player/components/index.ts
  src/features/player/components/profile/LeagueRecord.tsx
  src/features/player/components/profile/PlayerInfo.tsx
  src/features/player/hooks/usePlayer.tsx
  src/pages/player/CoachPage.tsx
  src/pages/player/detail/PlayerDetailPage.tsx
  src/store/useMaxStatsStore.ts
Labels: ✨ Feature

#108 Features/#107 경기 일정 반응형
  src/features/common/CustomSelect.tsx.tsx
  src/features/common/TeamInfo.tsx
  src/features/game/MatchScheduleTab.tsx
  src/features/game/components/calender/CalendarHeader.tsx
  src/features/game/components/calender/CalenderBody.tsx
  src/features/game/components/calender/MatchCalendar.tsx
  src/features/game/components/calender/MatchCalendarCell.tsx
  src/features/game/components/carousel/CarouselCard.tsx
  src/features/game/components/ranking/common/TeamRankingView.tsx
  src/features/game/hooks/boxscore/useBoxScore.tsx
Labels: ✨ Feature, 📪 API, 🛠️ Refactor

#106 Features/#105 코치 상세 페이지 반응형
  src/features/player/components/PlayerList.tsx
  src/pages/player/detail/CoachDetailPage.tsx
  src/pages/wizPark/IksanStadiumPage.tsx
Labels: ✨ Feature

#113 Features/#104 선수 페이지 타자 반영
  src/constants/chart-config.ts
  src/constants/columns/record-columns.tsx
  src/features/common/CustomBarChart.tsx
  src/features/common/CustomLineChart.tsx
  src/features/player/components/PlayerProfile.tsx
  src/features/player/components/PlayerRecordChart.tsx
  src/features/player/components/RecordTableAccordion.tsx
  src/features/player/components/SeasonSummary.tsx
  src/features/player/components/StatCard.tsx
  src/features/player/components/index.ts
  src/features/player/components/profile/LeagueRecord.tsx
  src/features/player/components/profile/PlayerInfo.tsx
  src/features/player/components/skeletons/PlayerProfileSkeleton.tsx
  src/features/player/hooks/usePlayer.tsx
  src/features/player/types/detail.ts
  src/pages/player/detail/PlayerDetailPage.tsx
  src/store/useMaxStatsStore.ts
  src/store/usePlayerStore.ts
Labels: 🐞 BugFix, 📪 API

#115 Features/#86 구단 연혁 퍼블리싱
  src/App.tsx
  src/pages/ktwiz/TeamHistory.tsx
Labels: ✨ Feature

#118 Features/#114 순위기록 페이지 다시 api 연결 & 반응형
  src/components/ui/select/select.tsx
  src/components/ui/tabs/tabs.tsx
  src/constants/columns/crowd-columns.tsx
  src/constants/columns/team-rank-colums.tsx
  src/features/common/CustomSelect.tsx.tsx
  src/features/common/SortableTable.tsx
  src/features/common/SubTabsTrigger.tsx
  src/features/game/components/ranking/batter/AllBatterRankingTab.tsx
  src/features/game/components/ranking/batter/BatterRankingTab.tsx
  src/features/game/components/ranking/batter/KTBatterRankingTab.tsx
  src/features/game/components/ranking/common/PlayerScatterChart.tsx
  src/features/game/components/ranking/common/RankingCard.tsx
  src/features/game/components/ranking/crowd/CrowdRankingChart.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/ranking/pitcher/AllPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/KTPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/PitcherRankingTab.tsx
  src/features/game/components/ranking/team/TeamRankingTab.tsx
  src/features/game/components/ranking/team/TeamRankingTable.tsx
  src/features/game/components/ranking/team/TeamVSTable.tsx
  src/pages/game/regular/RegularGamePage.tsx
Labels: ✨ Feature, 📪 API

#120 Features/#119 media api 확인 및 페이지 분리
  src/App.tsx
  src/constants/route.ts
  src/features/home/components/WizGallery.tsx
  src/features/home/components/WizVideo.tsx
  src/features/media/components/highlight/HighlightGridView.tsx
  src/lib/axios/instance.ts
  src/pages/media/id/HighlightDetail.tsx
Labels: 🐞 BugFix, 📪 API

#121 Features/#116 구단 연혁 페이지 반응형 적용
  src/App.tsx
  src/assets/data/ktHistory.json
  src/features/kwWiz/TeamHistoryTab.tsx
  src/features/kwWiz/TeamIntroduceTab.tsx
  src/features/kwWiz/index.ts
  src/pages/ktwiz/KtHistoryPage.tsx
  src/pages/ktwiz/TeamHistory.tsx
  src/pages/ktwiz/WallpaperPage.tsx
  src/pages/player/detail/CoachDetailPage.tsx
  src/pages/wizPark/IksanStadiumPage.tsx
  src/pages/wizPark/ParkLocationPage.tsx
Labels: ✨ Feature, 🛠️ Refactor

#123 Features/#122 로그인/회원가입 페이지 생성
  package-lock.json
  package.json
  src/App.tsx
  src/components/ui/checkbox/checkbox.tsx
  src/components/ui/index.ts
  src/components/ui/label/label.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
Labels: ✨ Feature
