Repository snifour/kt-wiz-snifour, pull requests merged in 2025-01, with the labels that each got.

#127 Features/#124 회원가입 폼 생성
  package-lock.json
  package.json
  src/App.tsx
  src/assets/data/agreement.json
  src/components/ui/index.ts
  src/components/ui/input/password-input.tsx
  src/features/auth/AgreementItem.tsx
  src/features/auth/SignupForm.tsx
  src/features/auth/schemas/loginSchema.ts
  src/features/auth/schemas/signupSchema.ts
  src/features/auth/types/agreements.ts
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
Labels: ✨ Feature

#130 Features/#128 media (포토 제외) api 연결
  src/App.tsx
  src/constants/route.ts
  src/constants/urls.ts
  src/features/common/Breadcrumb.tsx
  src/features/media/apis/firstPitch/firstPitchApi.query.ts
  src/features/media/apis/firstPitch/firstPitchApi.ts
  src/features/media/apis/highlight/HighlightApi.query.ts
  src/features/media/apis/highlight/HighlightApi.ts
  src/features/media/apis/story/StoryApi.query.ts
  src/features/media/apis/story/StoryApi.ts
  src/features/media/common/GridArticle.tsx
  src/features/media/common/MediaDetail.tsx
  src/features/media/common/SearchBar.tsx
  src/features/media/components/firstPitch/FirstPitchContent.tsx
  src/features/media/components/firstPitch/FirstPitchListView.tsx
  src/features/media/components/highlight/HighlightGridView.tsx
  src/features/media/components/news/NewsListView.tsx
  src/features/media/components/story/StoryContent.tsx
  src/features/media/components/story/StoryGridView.tsx
  src/features/media/hooks/firstPitch/useFirstPitchDetailQuery.ts
  src/features/media/hooks/firstPitch/useFirstPitchListQuery.ts
  src/features/media/hooks/highlight/useHighLightDetailQuery.ts
  src/features/media/hooks/highlight/useHighlightListQuery.ts
  src/features/media/hooks/news/useNewsDetailQuery.ts
  src/features/media/hooks/news/useNewsListQuery.ts
  src/features/media/hooks/news/usePressDetailQuery.ts
  src/features/media/hooks/story/useStoryDetailQuery.ts
  src/features/media/hooks/story/useStoryListQuery.ts
  src/features/media/services/grid-mapper.service.ts
  src/features/media/services/list-mapper.service.ts
  src/features/media/types/firstPitch.ts
  src/features/media/types/highlight.ts
  src/features/media/types/story.ts
  src/lib/helpers/html-parser.ts
  src/pages/media/FirstPitchPage.tsx
  src/pages/media/HighlightPage.tsx
  src/pages/media/NewsPage.tsx
  src/pages/media/PhotoPage.tsx
  src/pages/media/StoryPage.tsx
  src/pages/media/id/FirstPitchDetailPage.tsx
  src/pages/media/id/HighlightDetail.tsx
  src/pages/media/id/HighlightDetailPage.tsx
  src/pages/media/id/NewsDetailPage.tsx
  src/pages/media/id/PressDetailPage.tsx
  src/pages/media/id/StoryDetailPage.tsx
Labels: ✨ Feature, 📪 API

#133 Features/#132 관전 포인트 API 연동
  src/features/game/BoxScoreTab.tsx
  src/features/game/WatchPointTab.tsx
  src/features/game/apis/watch-point.ts
  src/features/game/components/card/KeyRecordsCard.tsx
  src/features/game/components/carousel/MatchInfoCarousel.tsx
  src/features/game/components/common/MatchBoard.tsx
  src/features/game/components/common/index.ts
  src/features/game/components/index.ts
  src/features/game/components/watch-point/index.ts
  src/features/game/hooks/common/useRecentMatches.tsx
  src/features/game/types/watch-point.ts
Labels: ✨ Feature, 📪 API

#134 Features/#131 포토 api 연결
  src/constants/route.ts
  src/features/media/apis/photo/PhotoApi.query.ts
  src/features/media/apis/photo/PhotoApi.ts
  src/features/media/common/GridArticle.tsx
  src/features/media/components/photo/DateRangePicker.tsx
  src/features/media/components/photo/PhotoContent.tsx
  src/features/media/components/photo/PhotoFilter.tsx
  src/features/media/components/photo/PhotoGridView.tsx
  src/features/media/css/media.css
  src/features/media/hooks/photo/usePhotoListQuery.ts
  src/features/media/services/grid-mapper.service.ts
  src/features/media/types/grid.ts
  src/features/media/types/photo.ts
  src/pages/media/PhotoPage.tsx
Labels: 📪 API

#136 Featuers/#129 애니메이션 테스트 및 적용
  package-lock.json
  package.json
  src/features/game/components/watch-point/TeamLineup.tsx
  src/features/game/components/watch-point/TeamLineupAnimation.tsx
  src/features/game/components/watch-point/index.ts
  src/features/home/components/WizGallery.tsx
  src/features/home/components/WizGalleryAnimationItem.tsx
  src/features/home/components/WizVideo.tsx
  src/features/home/components/WizVideoAnimation.tsx
  src/features/home/index.ts
Labels: ✨ Feature

#137 Features/#126 치어리더 페이지 API 연결
  src/features/common/SubTabsTrigger.tsx
  src/features/game/components/ranking/batter/AllBatterRankingTab.tsx
  src/features/game/components/ranking/batter/BatterRankingTab.tsx
  src/features/game/components/ranking/batter/KTBatterRankingTab.tsx
  src/features/game/components/ranking/crowd/CrowdRankingChart.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/ranking/pitcher/AllPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/KTPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/PitcherRankingTab.tsx
  src/features/player/apis/cheerleader.ts
  src/features/player/apis/index.ts
  src/features/player/components/CheerleaderDialog.tsx
  src/features/player/components/PlayerProfile.tsx
  src/features/player/components/PlayerRecordChart.tsx
  src/features/player/components/RecordTableAccordion.tsx
  src/features/player/components/SeasonSummary.tsx
  src/features/player/components/cheerleader/CheerleaderDialog.tsx
  src/features/player/components/profile/LeagueRecord.tsx
  src/features/player/hooks/useCheerleaderList.tsx
  src/features/player/hooks/usePlayer.tsx
  src/features/player/types/cheerleader.ts
  src/pages/player/CheerLeaderPage.tsx
  src/pages/player/detail/PlayerDetailPage.tsx
Labels: ✨ Feature, 📪 API

#140 Features/#138 Player 검색 기능 추가
  src/features/player/CatcherTab.tsx
  src/features/player/InfielderTab.tsx
  src/features/player/OutfielderTab.tsx
  src/features/player/components/PlayerList.tsx
  src/pages/player/CoachPage.tsx
  src/pages/player/PitcherPage.tsx
Labels: ✨ Feature

#144 fix: 박스스코어 날짜 포맷팅 오류 해결(#142)
  src/features/game/BoxScoreTab.tsx
  src/features/game/components/common/MatchBoard.tsx
Labels: 🐞 BugFix

#143 Features/#135 media 무한 스크롤 구현
  package-lock.json
  package.json
  src/features/media/apis/highlight/HighlightApi.query.ts
  src/features/media/apis/highlight/HighlightApi.ts
  src/features/media/apis/photo/PhotoApi.query.ts
  src/features/media/apis/story/StoryApi.query.ts
  src/features/media/components/highlight/HighlightGridView.tsx
  src/features/media/components/photo/PhotoGridView.tsx
  src/features/media/components/story/StoryGridView.tsx
  src/features/media/hooks/highlight/useHighlightListQuery.ts
  src/features/media/hooks/photo/usePhotoListQuery.ts
  src/features/media/hooks/story/useStoryListQuery.ts
  src/features/media/types/grid.ts
  src/features/media/types/highlight.ts
  src/features/media/types/photo.ts
  src/lib/react-query/use-query-params.ts
Labels: ✨ Feature

#147 Features/#141 공통 컴포넌트(Breadcrumb, SearchBar) 반응형 설정
  src/constants/urls.ts
  src/features/common/Breadcrumb.tsx
  src/features/media/common/SearchBar.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
Labels: ✨ Feature

#149 Features/#145 선수 페이지 수정
  package-lock.json
  src/features/common/ChartLabelList.tsx
  src/features/common/SubTabsTrigger.tsx
  src/features/game/components/ranking/common/TeamRankingView.tsx
  src/features/player/components/detail/PlayerProfile.tsx
  src/features/player/components/detail/PlayerRecordChart.tsx
  src/features/player/components/detail/RecentRecordTab.tsx
  src/features/player/components/detail/RecordTableAccordion.tsx
  src/features/player/components/detail/SeasonSummary.tsx
  src/features/player/components/detail/StatCard.tsx
  src/features/player/components/detail/profile/LeagueRecord.tsx
  src/features/player/components/detail/profile/PlayerInfo.tsx
  src/features/player/components/index.ts
  src/pages/player/detail/PlayerDetailPage.tsx
Labels: 🐞 BugFix

#152 Features/#148 경기 일정 불러오는 함수 분리
  src/constants/chart-config.ts
  src/features/game/components/carousel/MatchInfoCarousel.tsx
  src/features/player/components/detail/PlayerProfile.tsx
  src/features/player/components/detail/PlayerRecordChart.tsx
  src/features/player/components/detail/RecentRecordTab.tsx
  src/hooks/useMatchSchedule.tsx
  src/pages/player/detail/PlayerDetailPage.tsx
Labels: 🛠️ Refactor

#156 Features/#153 기타 페이지 생성
  public/assets/Ktwiz/donation-program.jpg
  public/assets/Ktwiz/general-member.jpg
  src/App.tsx
  src/features/kwWiz/components/DonationProgramTab.tsx
  src/features/kwWiz/components/GeneralMemberTab.tsx
  src/features/kwWiz/components/TeamHistoryTab.tsx
  src/features/kwWiz/components/TeamIntroduceTab.tsx
  src/features/kwWiz/index.ts
  src/pages/ktwiz/MembershipPolicyPage.tsx
Labels: ✨ Feature

#154 Features/#150 순위기록 필터링
  src/constants/route.ts
  src/constants/seasons.ts
  src/features/common/SortableTable.tsx
  src/features/common/types/batters.ts
  src/features/common/types/pitchers.ts
  src/features/game/apis/ranking/batter.ts
  src/features/game/apis/ranking/pitcher.ts
  src/features/game/apis/ranking/rankingApi.query.ts
  src/features/game/apis/ranking/rankingApi.ts
  src/features/game/components/ranking/batter/AllBatterRankingTab.tsx
  src/features/game/components/ranking/batter/BatterRankingTab.tsx
  src/features/game/components/ranking/batter/KTBatterRankingTab.tsx
  src/features/game/components/ranking/common/Filter.tsx
  src/features/game/components/ranking/common/PlayerScatterChart.tsx
  src/features/game/components/ranking/common/RankingCard.tsx
  src/features/game/components/ranking/pitcher/AllPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/KTPitcherRankingTab.tsx
  src/features/game/components/ranking/pitcher/PitcherRankingTab.tsx
  src/features/game/hooks/ranking/useBatterRank.tsx
  src/features/game/hooks/ranking/usePitcherRank.tsx
  src/features/game/hooks/ranking/useTopBatterRank.tsx
  src/features/game/hooks/ranking/useTopPitcherRank.tsx
  src/features/game/types/ranking.ts
Labels: ✨ Feature, 📪 API

#159 Features/#157 경기 일정 리액트 쿼리
  .gitignore
  src/constants/route.ts
  src/features/common/TeamInfo.tsx
  src/features/game/apis/match-schedule/matchScheduleApi.query.ts
  src/features/game/apis/match-schedule/matchScheduleApi.ts
  src/features/game/components/calender/MatchCalendar.tsx
  src/features/game/components/calender/MatchCalendarCell.tsx
  src/features/game/components/carousel/CarouselCard.tsx
  src/features/game/components/carousel/MatchInfoCarousel.tsx
  src/features/game/types/match-schedule.ts
  src/hooks/useMatchSchedule.tsx
  src/pages/ktwiz/KtHistoryPage.tsx
  src/pages/media/NewsPage.tsx
  src/pages/media/PhotoPage.tsx
Labels: ✨ Feature, 🛠️ Refactor

#160 Features/#155 순위 기록 리액트 쿼리 작업
  src/constants/route.ts
  src/features/game/apis/ranking/rankingApi.query.ts
  src/features/game/apis/ranking/rankingApi.ts
  src/features/game/components/ranking/batter/BatterRankingTab.tsx
  src/features/game/components/ranking/common/Filter.tsx
  src/features/game/components/ranking/common/RankingCard.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/ranking/pitcher/PitcherRankingTab.tsx
  src/features/game/components/ranking/team/TeamBatterRankingView.tsx
  src/features/game/components/ranking/team/TeamPitcherRankingView.tsx
  src/features/game/components/ranking/team/TeamRankingTable.tsx
  src/features/game/components/ranking/team/TeamVSTable.tsx
  src/features/game/hooks/ranking/useCrowdRank.tsx
  src/features/game/hooks/ranking/useTeamRank.tsx
  src/features/game/hooks/ranking/useTeamVS.tsx
  src/features/game/hooks/ranking/useTopBatterRank.tsx
  src/features/game/hooks/ranking/useTopPitcherRank.tsx
  src/features/game/services/arrange-vs.service.ts
  src/features/game/types/crowd-ranking.ts
  src/features/game/types/ranking.ts
  src/features/game/types/team-ranking.ts
  src/features/media/components/highlight/HighlightGridView.tsx
  src/index.css
Labels: 🐞 BugFix, 📪 API

#163 Featuers/#161 수파베이스 DB 연동
  package-lock.json
  package.json
  src/App.tsx
  src/components/ui/index.ts
  src/constants/api-url.ts
  src/features/auth/components/AgreementItem.tsx
  src/features/auth/components/EditProfileDialog.tsx
  src/features/auth/components/SignupForm.tsx
  src/features/auth/hooks/useAuthRedirect.ts
  src/features/auth/hooks/useLogin.ts
  src/features/auth/hooks/useSignup.ts
  src/features/auth/hooks/useUserSession.ts
  src/features/auth/index.ts
  src/features/auth/schemas/signupSchema.ts
  src/features/common/header/Sidebar.tsx
  src/features/common/header/WebHeader.tsx
  src/lib/supabase.ts
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/store/useUserStore.ts
Labels: ✨ Feature

#164 Features/#162 선수 페이지 리액트쿼리
  src/constants/route.ts
  src/features/game/apis/ranking/crowd.ts
  src/features/game/apis/ranking/rankingApi.ts
  src/features/game/apis/ranking/team.ts
  src/features/player/CatcherTab.tsx
  src/features/player/InfielderTab.tsx
  src/features/player/OutfielderTab.tsx
  src/features/player/apis/playerApi.query.ts
  src/features/player/apis/playerApi.ts
  src/features/player/components/PlayerList.tsx
  src/features/player/components/detail/PlayerProfile.tsx
  src/features/player/components/detail/RecentRecordTab.tsx
  src/features/player/components/detail/SeasonSummary.tsx
  src/features/player/components/detail/profile/LeagueRecord.tsx
  src/features/player/components/detail/profile/PlayerInfo.tsx
  src/features/player/hooks/useCoach.tsx
  src/features/player/hooks/useCoachList.tsx
  src/features/player/hooks/useMaxStats.tsx
  src/features/player/hooks/usePlayer.tsx
  src/features/player/hooks/usePlayerList.tsx
  src/features/player/hooks/usePlayerSearch.tsx
  src/features/player/services/find-maxstats.service.ts
  src/features/player/types/list.ts
  src/features/player/types/player.ts
  src/pages/player/BatterPage.tsx
  src/pages/player/CoachPage.tsx
  src/pages/player/PitcherPage.tsx
  src/pages/player/detail/CoachDetailPage.tsx
  src/pages/player/detail/PlayerDetailPage.tsx
  src/store/usePlayerStore.ts
Labels: 📪 API, 🛠️ Refactor

#167 Features/#166 경기 일정, 관전포인트 api 호출 함수 리액트쿼리
  src/constants/route.ts
  src/features/auth/hooks/useLogin.ts
  src/features/common/DataTable.tsx
  src/features/game/WatchPointTab.tsx
  src/features/game/apis/match-schedule/RecentScheduleApi.query.ts
  src/features/game/apis/match-schedule/matchScheduleApi.query.ts
  src/features/game/apis/match-schedule/matchScheduleApi.ts
  src/features/game/apis/watch-point/watchPointApi.query.ts
  src/features/game/apis/watch-point/watchPointApi.ts
  src/features/game/components/carousel/CarouselCard.tsx
  src/features/game/components/carousel/MatchInfoCarousel.tsx
  src/features/game/hooks/common/useRecentMatches.tsx
  src/features/game/hooks/watch-point/useWatchPoint.tsx
  src/features/game/types/match-schedule.ts
  src/store/useMatchStore.ts
Labels: ✨ Feature, 📪 API, 🛠️ Refactor

#168 Features/#139 챗봇
  package-lock.json
  package.json
  src/App.tsx
  src/features/chatbot/ActionProvider.tsx
  src/features/chatbot/Header.tsx
  src/features/chatbot/MessageParser.tsx
  src/features/chatbot/WidgetButton.tsx
  src/features/chatbot/WizAvatar.tsx
  src/features/chatbot/chatbot.css
  src/features/chatbot/config.ts
Labels: ✨ Feature

#171 Features/#170 관전 포인트 스켈레톤
  src/features/game/WatchPointTab.tsx
  src/features/game/apis/index.ts
  src/features/game/apis/match-schedule.ts
  src/features/game/apis/match-schedule/RecentScheduleApi.query.ts
  src/features/game/apis/watch-point.ts
  src/features/game/components/calender/CalendarHeader.tsx
  src/features/game/components/carousel/MatchInfoCarousel.tsx
  src/lib/helpers/parse-date.ts
  src/store/useMatchStore.ts
Labels: ✨ Feature, 🛠️ Refactor

#174 Features/#165 메인페이지 리액트 쿼리 및 스켈레톤
  public/assets/main/img-score@2x.png
  src/constants/route.ts
  src/features/game/apis/match-schedule/matchScheduleApi.query.ts
  src/features/home/apis/mainApi.query.ts
  src/features/home/apis/mainApi.ts
  src/features/home/components/MatchInfo.tsx
  src/features/home/components/MatchInfoCard.tsx
  src/features/home/components/RecentMatches.tsx
  src/features/home/components/TeamRanking.tsx
  src/features/home/components/WizGallery.tsx
  src/features/home/components/WizGalleryAnimationItem.tsx
  src/features/home/components/WizVideo.tsx
  src/features/home/components/WizVideoAnimation.tsx
  src/features/home/types/index.ts
Labels: ✨ Feature, 📪 API

#177 Featuers/#172 구글 소셜로그인
  public/assets/auth/google_logo.png
  public/assets/auth/kakao_logo.png
  src/features/auth/components/EditProfileDialog.tsx
  src/features/auth/hooks/useGoogleLogin.ts
  src/features/auth/hooks/useLogin.ts
  src/features/auth/hooks/useUserSession.ts
  src/pages/auth/LoginPage.tsx
Labels: ✨ Feature, 📪 API, 🛠️ Refactor

#178 Features/#169 박스스코어 리액트 쿼리 적용
  src/constants/columns/batting-record-columns.ts
  src/constants/columns/pitching-record-columns.ts
  src/constants/route.ts
  src/features/game/BoxScoreTab.tsx
  src/features/game/apis/boxscore/boxscore.ts
  src/features/game/apis/boxscore/boxscoreApi.query.ts
  src/features/game/apis/boxscore/boxscoreApi.ts
  src/features/game/components/card/KeyRecordsCard.tsx
  src/features/game/components/table/BattingRecordTable.tsx
  src/features/game/components/table/KeyRecordsTable.tsx
  src/features/game/components/table/MatchScoreTable.tsx
  src/features/game/components/table/PitchingRecordTable.tsx
  src/features/game/components/table/index.ts
  src/features/game/hooks/boxscore/useBoxScore.tsx
  src/features/game/hooks/boxscore/usePlayerImage.tsx
  src/features/game/types/boxscore.ts
Labels: 🐞 BugFix, 🛠️ Refactor

#184 feat: 코치 상세 페이지 스켈레톤 적용
  src/pages/player/detail/CoachDetailPage.tsx
Labels: ✨ Feature

#181 Features/#180 빌드 확인
  .gitignore
  src/constants/columns/crowd-columns.tsx
  src/constants/columns/season-summary-columns.tsx
  src/constants/columns/team-rank-colums.tsx
  src/features/game/components/ranking/batter/AllBatterRankingTab.tsx
  src/features/game/components/ranking/batter/BatterRankingTab.tsx
  src/features/game/components/ranking/common/chart/CustomTooltip.tsx
  src/features/game/components/ranking/common/chart/PlayerScatterChart.tsx
  src/features/game/components/ranking/crowd/CrowdRankingTab.tsx
  src/features/game/components/ranking/pitcher/PitcherRankingTab.tsx
  src/features/player/components/detail/RecordTableAccordion.tsx
  src/features/player/index.ts
Labels: ✨ Feature, 📪 API

#187 Features/#185: 무한스크롤 데이터가 존재하지 않을 때 버그 수정
  src/features/media/apis/highlight/HighlightApi.query.ts
  src/features/media/apis/photo/PhotoApi.query.ts
  src/features/media/apis/story/StoryApi.query.ts
  src/features/media/components/highlight/HighlightGridView.tsx
  src/features/media/components/photo/PhotoGridView.tsx
  src/features/media/components/story/StoryGridView.tsx
Labels: 🐞 BugFix

#192 Features/#188 UI 버그 수정
  src/features/auth/components/EditProfileDialog.tsx
  src/features/chatbot/chatbot.css
  src/features/common/Banner.tsx
  src/features/common/DataTable.tsx
  src/features/common/SortableTable.tsx
  src/features/common/header/WebHeader.tsx
Labels: 🐞 BugFix

#190 features/#183 카카오 로그인
  src/features/auth/hooks/useKakaoLogin.ts
  src/pages/auth/LoginPage.tsx
Labels: ✨ Feature, 📪 API

#189 FIX/#186 캐러셀 전체 경기 보여주는 오류 해결
  src/features/game/apis/match-schedule/matchScheduleApi.query.ts
Labels: 🐞 BugFix, 📪 API

#195 features/117 티켓 예매 탭 추가
  src/App.tsx
  src/features/ticket/components/TicketItem.tsx
  src/features/ticket/components/TicketPriceTab.tsx
  src/features/ticket/components/TicketReservationTab.tsx
  src/pages/ticketpurchase/TicketPurchasePage.tsx
Labels: ✨ Feature

#196 Features/#191 박스스코어 오류 수정
  public/assets/ticketpurchase/seat.png
  src/App.tsx
  src/features/game/BoxScoreTab.tsx
  src/features/game/apis/boxscore/boxscoreApi.query.ts
  src/features/game/apis/boxscore/boxscoreApi.ts
  src/features/game/components/card/KeyRecordsCard.tsx
  src/features/ktWiz/components/DonationProgramTab.tsx
  src/features/ktWiz/components/GeneralMemberTab.tsx
  src/features/ktWiz/components/TeamHistoryTab.tsx
  src/features/ktWiz/components/TeamIntroduceTab.tsx
  src/features/ktWiz/index.ts
  src/features/ticket/components/TicketPriceTab.tsx
  src/pages/ktwiz/KtHistoryPage.tsx
  src/pages/ktwiz/MembershipPolicyPage.tsx
Labels: 🐞 BugFix, 🛠️ Refactor

#198 Features/#197 랭킹 카드 오류 수정
  src/features/game/components/ranking/common/RankingCard.tsx
Labels: 🐞 BugFix

#202 Features/#199 선발투수 차트 반응형
  src/features/game/WatchPointTab.tsx
  src/features/game/components/watch-point/StartingPitcherChart.tsx
  src/features/game/components/watch-point/index.ts
  src/features/game/services/calc-rate-watchpoint.service.ts
Labels: ✨ Feature

#201 Featuers/#200 티켓 예매 반응형
  src/features/ticket/components/LoginConfirmationDialog.tsx
  src/features/ticket/components/TicketItem.tsx
  src/features/ticket/components/TicketPriceTab.tsx
  src/features/ticket/components/TicketReservationTab.tsx
  src/features/ticket/index.ts
  src/pages/ticketpurchase/TicketPurchasePage.tsx
Labels: ✨ Feature, 🛠️ Refactor

#203 fix: 선발투수 비교 함수 수정(#199)
  src/features/game/services/calc-rate-watchpoint.service.ts
Labels: 🐞 BugFix

#205 Featuers/#204
  src/features/game/BoxScoreTab.tsx
  src/features/game/components/card/KeyRecordsCard.tsx
Labels: ✨ Feature

#209 FEAT 정규리그 탭에따른 subtitle 변경
  src/pages/game/regular/RegularGamePage.tsx
Labels: ✨ Feature

#212 subtitle 색상 원상복구
  src/features/auth/components/EditProfileDialog.tsx
  src/features/auth/hooks/useGoogleLogin.ts
  src/features/common/components/SubTitle.tsx
  src/features/home/components/MatchInfo.tsx
  src/features/home/components/MatchInfoCard.tsx
  src/lib/helpers/parse-date.ts
Labels: 🐞 BugFix

#215 fix: 타입 import 수정(#213)
  src/features/game/components/watch-point/StartingPitcherChart.tsx
  src/features/game/components/watch-point/StartingPitcherTable.tsx
Labels: 🐞 BugFix

#216 build: mixed contents 에러 수정(#213)
  index.html
Labels: 🌏 Deploy

#217 fix: api url 수정(#213)
  index.html
  src/features/player/components/detail/PlayerRecordChart.tsx
Labels: 🐞 BugFix, 🌏 Deploy

#219 Features/#218 리드미 작성
  README.md
Labels: 📜 Docs
